# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce8b9c690e720d6da47a4b9a63c507382654b07d7bd0e311770c2911962086b617a9f1da239ccf0bb116189d230702d6007741f4587dd1c635062a8453b1268c

test:
  secret_key_base: aefcf378b4ca1e84b3a5ad985f5e3cc79e54735c80c928e006476b6bf6e06de69d8002028d1e3340012251f6d95896d39c63aa42e44a4cf81bd247f4a98680b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
